# initial setup for docker-compose.yml
version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --appendonly yes

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  api:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
